exclude_paths:
  - 'LICENSE'
  - 'README.md'
  - 'gulpfile.js'
  - '.travis.yml'
  - 'bdd/**'
  - 'ressources/_img/**'
  - 'ressources/css/agency.css'
  - 'ressources/css/agency.min.css'
  - 'ressources/js/**'
  - 'ressources/scss/**/*'
  - 'ressources/pdf/**'
  - 'ressources/fonts/**'
  - 'diagrams/**/*'
  - 'vendor/**/*'
  - 'ressources/js/**'